import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLeaf } from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
      <div id="Navigation-Bar">
        <h1 id="Logo"></h1>
        <FontAwesomeIcon id="Maple" icon={faLeaf}/>
        <div id="Navigation">
          <ul id="Left-Nav">
            <li>Daily Challenge</li>
            <li>Practice</li>
            <li>Learn</li>
          </ul>
          <ul id="Right-Nav" >
            <li>Login</li>
            <li>Register</li>
          </ul>
      </div>
      </div>
      <div className={inter.className}>{children}</div>      
      </body>
    </html>
  );
}
